name: Gitleaks

on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run gitleaks
            run:  docker run -v ${{ github.workspace }}:/path zricethezav/gitleaks:latest detect -v --source="/path"  --redact --report-format sarif --report-path="/path/results.sarif" --exit-code=0
          - name: workspace
            run: echo ${{ github.workspace }}
          - name: ls  
            run: ls -la 
          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v2
            with:
              # Path to SARIF file relative to the root of the repository
              sarif_file: results.sarif
              # Optional category for the results
              category: my-analysis-tool
          
        

  